### ISSUE TITLE
CONTRIBUTING.md references non-existent dev branch

### ISSUE THREAD

**Issue by tyler-dot-earth** [catppuccin/.github#3]
whilst reviewing the [CONTRIBUTING.md](https://github.com/catppuccin/.github/blob/f2340fe989da75a16014d8f21b6b098f3e380ace/CONTRIBUTING.md?plain=1#L23) for [this PR](https://github.com/catppuccin/nvim/pull/502), i noticed that it referenced a `dev` branch that does not exist for [catppuccin/nvim](https://github.com/catppuccin/nvim)

~~guessing that the CONTRIBUTING file was borrowed from somewhere else or is just old process, but documenting regardless.~~ seems to be a common file for all `catppuccin` repos?

**Comment by tyler-dot-earth** [comment]
oh... interesting — i somehow ended up in this PR from [catppuccin/nvim](https://github.com/catppuccin/nvim/pull/502) via this link [in my PR for that repo](https://github.com/catppuccin/nvim/pull/502):
<img width="611" alt="Screenshot 2023-06-03 at 6 43 03 PM" src="https://github.com/catppuccin/.github/assets/595711/41f0357d-89e5-4bfe-ad60-dc29106ef6ed">

if there's somewhere.. more helpful for me to leave this feedback, please let me know 👍

**Comment by nekowinston** [comment]
Hey there 👋 

You've been redirected here since the nvim repo uses our global CONTRIBUTING.md 🙂.

And good catch, thank you! We got rid of recommending the dev-branch in catppuccin/catppuccin, but forgot about this one. We used to recommend the dev branch approach until the [start of this year](https://github.com/catppuccin/catppuccin/commit/b9bbd77c7fa1c11da6b700b01b173410a760e1e9).

**Comment by tyler-dot-earth** [comment]
> Hey there 👋
> 
> You've been redirected here since the nvim repo uses our global CONTRIBUTING.md 🙂.
> 
> And good catch, thank you! We got rid of recommending the dev-branch in catppuccin/catppuccin, but forgot about this one. We used to recommend the dev branch approach until the [start of this year](https://github.com/catppuccin/catppuccin/commit/b9bbd77c7fa1c11da6b700b01b173410a760e1e9).

Thanks for the context — here's a PR that just removes content and tells you to use `main` instead: https://github.com/catppuccin/.github/pull/4
